### ISSUE TITLE
404 error when trying to sync

### ISSUE THREAD

**Issue by yvangodard** [b4tman/sync_ics2gcal#79]
Hi,
I'm trying to use your tool, but i'm facing en issue :

Traceback (most recent call last):
  File "/home/sync-ic2gcal/venv/bin/sync-ics2gcal", line 8, in <module>
    sys.exit(main())
  File "/home/sync-ic2gcal/venv/lib/python3.7/site-packages/sync_ics2gcal/sync_calendar.py", line 49, in main
    sync.prepare_sync(start)
  File "/home/sync-ic2gcal/venv/lib/python3.7/site-packages/sync_ics2gcal/sync.py", line 146, in prepare_sync
    events_dst = self.gcalendar.list_events_from(start_date)
  File "/home/sync-ic2gcal/venv/lib/python3.7/site-packages/sync_ics2gcal/gcal.py", line 140, in list_events_from
    fields=fields).execute()
  File "/home/sync-ic2gcal/venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/sync-ic2gcal/venv/lib/python3.7/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/9i2mpeeook2iam2hdfhpjs2nuk%40group.calendar.google.com/events?singleEvents=true&timeMin=2022-02-20T08%3A25%3A34.434038Z&fields=nextPageToken%2Citems%28id%2CiCalUID%2Cupdated%29&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">

I checked gcalendar Id, ICS file, etc. but no idea to solve it ...
Could you help me ?

**Comment by b4tman** [comment]
Hi @yvangodard.  
Please check `manage-ics2gcal list` (or `poetry run manage-ics2gcal list`), output. 
Does requested calendar is shown?

**Comment by b4tman** [comment]
> I checked gcalendar Id, ICS file, etc. but no idea to solve it ...

i got this errors when google calendar id is wrong, so please double check it

**Comment by yvangodard** [comment]
@b4tman no output when trying manage-ics2gcal list

**Comment by b4tman** [comment]
> @b4tman no output when trying manage-ics2gcal list

try creating one (`poetry run manage-ics2gcal create --help`)
If it appears in list, then you can use it with `sync-ics2gcal`. 
If you want to use calendar owned by other user, then you need to add access to that calendar (share) to you service account.

**Comment by yvangodard** [comment]
@b4tman in fact it works when trying to create a calendar from your tool and the API. It wasn’t clear for me that sync works only for calendars associated to the API service account.
Thanks a lot for your help !
