### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by yvangodard** [b4tman/sync_ics2gcal#80]
Hi, after a first sync, I'm facing this issue when trying to re-sync : 

Traceback (most recent call last):
  File "/usr/local/bin/sync-ics2gcal", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/sync_ics2gcal/sync_calendar.py", line 49, in main
    sync.prepare_sync(start)
  File "/usr/local/lib/python3.7/dist-packages/sync_ics2gcal/sync.py", line 169, in prepare_sync
    self._filter_events_to_update()
  File "/usr/local/lib/python3.7/dist-packages/sync_ics2gcal/sync.py", line 79, in _filter_events_to_update
    self.to_update = list(filter(filter_updated, self.to_update))
  File "/usr/local/lib/python3.7/dist-packages/sync_ics2gcal/sync.py", line 75, in filter_updated
    new_date = dateutil.parser.parse(new['updated'])
KeyError: 'updated'

What could be the reason ? Any idea to solve this issue ?

**Comment by b4tman** [comment]
Hi, @yvangodard. Looks like source ics file events don't have 'LAST-MODIFIED' field, that used to compare with 'updated' field on google calendar events. 

I need to figure out how to handle such events, may be using 'CREATED' or 'DTSTART' fields, or just always overwrite it.

**Comment by yvangodard** [comment]
Exactly, some events don't have LAST-MODIFIED field. For sure, always overwriting this type of events would be a solution.

**Comment by b4tman** [comment]
@yvangodard I just pushed a fix to develop branch, please help test again!

**Comment by yvangodard** [comment]
I'm trying to install your last update with poetry, but facing an issue ...
I'm not very familiar with poetry, so if you have an idea to solve this, feel free to tell me.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ical2googlesync/sync-ics2gcal/sync_ics2gcal/sync_ics2gcal/__init__.py", line 2, in <module>
    from .ical import (
  File "/home/ical2googlesync/sync-ics2gcal/sync_ics2gcal/sync_ics2gcal/ical.py", line 5, in <module>
    from icalendar import Calendar, Event
ModuleNotFoundError: No module named 'icalendar'

**Comment by b4tman** [comment]
> ModuleNotFoundError: No module named 'icalendar'

try:
```bash
poetry install
```
it will install dependencies in virtual environment.
then you can run:
```bash
poetry run sync-ics2gcal
```

**Comment by yvangodard** [comment]
Thanks, I saw just after posting that I was trying to run without having install ...
Regard my tests it seems to work well. 
Just an issue when trying to use a config start_from with a specific date :

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ical2googlesync/sync-ics2gcal/sync_ics2gcal/sync_calendar.py", line 40, in main
    start = get_start_date(config['start_from'])
  File "/home/ical2googlesync/sync-ics2gcal/sync_ics2gcal/sync_calendar.py", line 27, in get_start_date
    result = dateutil.parser.parse(date_str)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 70, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not datetime

**Comment by b4tman** [comment]
> TypeError: Parser must be a string or character stream, not datetime


use quotes, like this:
```yaml
start_from: '2018-04-03T13:23:25.000001Z'
```

i will fix it

**Comment by yvangodard** [comment]
Everything seems to work perfectly now! Great! 👍
