### ISSUE TITLE
config: `start_from` can be already parsed datetime

### ISSUE THREAD

**Issue by b4tman** [b4tman/sync_ics2gcal#82]
Just an issue when trying to use a config start_from with a specific date :

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ical2googlesync/sync-ics2gcal/sync_ics2gcal/sync_calendar.py", line 40, in main
    start = get_start_date(config['start_from'])
  File "/home/ical2googlesync/sync-ics2gcal/sync_ics2gcal/sync_calendar.py", line 27, in get_start_date
    result = dateutil.parser.parse(date_str)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal--yUbY2jh-py3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 70, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not datetime

_Originally posted by @yvangodard in https://github.com/b4tman/sync_ics2gcal/issues/80#issuecomment-1048604196_

**Comment by b4tman** [comment]
fixed
