### ISSUE TITLE
Authentification erro

### ISSUE THREAD

**Issue by yvangodard** [b4tman/sync_ics2gcal#83]
Sorry, but a new issue appears after installation the latest developper branch version, when trying to create a new calendar :

root@DEB10-ICS2GCALSYNC:/home/ical2googlesync/sync_ics2gcal# poetry run manage-ics2gcal create Yvan
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ical2googlesync/sync_ics2gcal/sync_ics2gcal/manage_calendars.py", line 140, in main
    fire.Fire(Commands, name='manage-ics2gcal')
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal-YErR-sF2-py3.7/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal-YErR-sF2-py3.7/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal-YErR-sF2-py3.7/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ical2googlesync/sync_ics2gcal/sync_ics2gcal/manage_calendars.py", line 63, in __init__
    self._service = GoogleCalendarService.from_config(self._config)
  File "/home/ical2googlesync/sync_ics2gcal/sync_ics2gcal/gcal.py", line 65, in from_config
    service = GoogleCalendarService.default()
  File "/home/ical2googlesync/sync_ics2gcal/sync_ics2gcal/gcal.py", line 30, in default
    credentials, _ = google.auth.default(scopes=scopes)
  File "/root/.cache/pypoetry/virtualenvs/sync-ics2gcal-YErR-sF2-py3.7/lib/python3.7/site-packages/google/auth/_default.py", line 575, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

**Comment by b4tman** [comment]
@yvangodard please check `service_account` field in your `config.yml` file
